### ISSUE TITLE
TypeError: plugin.apply is not a function

### ISSUE THREAD

**Issue by Syrup** [tylingsoft/markdown-it-highlight#2]
i got TypeError: plugin.apply is not a function xD

**Comment by franciscop** [comment]
To further expand on Miouns, after installing `markdown-it@11.0.0` and `markdown-it-highlight@0.2.0`, given this code:

```js
import MarkdownIt from "markdown-it";
import markdownItHighlight from "markdown-it-highlight";

const md = new MarkdownIt();
md.use(markdownItHighlight);
```

An error is thrown **when running on a modern Node.js version with ESM**:

```
/home/francisco/projects/documentation/node_modules/markdown-it/lib/index.js:496
  plugin.apply(plugin, args);
         ^

TypeError: plugin.apply is not a function
    at MarkdownIt.use (/home/francisco/projects/documentation/node_modules/markdown-it/lib/index.js:496:10)
```

## Solution

Inspecting the `markdownItHighlight` we can see that it is 

```js
console.log(markdownItHighlight);
{ default: [function:o] }
```

This is because I'm using a modern Node.js version with ESM; instead, if you do this it should work:

```js
import MarkdownIt from "markdown-it";
import markdownItHighlight from "markdown-it-highlight";

const md = new MarkdownIt();
md.use(markdownItHighlight.default);
```

> PS: but this library is not doing what I thought it was doing, so it's not useful for me...

**Comment by Syrup** [comment]
it worked, thanks
